# CI de Nivel 04 - Disparo dos testes dentro do pipe de dev
# v6

name: "Execução Integrada"

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Instalando Playwright e navegadores
        run: npx playwright install --with-deps

      - name: Executando Testes E2E
        run: yarn e2e

      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Simulação do Deploy
        run: echo "Simulando o deploy com sucesso"
